# -*- coding: utf-8 -*-
"""zoop_chatbot_gpt_3_5_turbo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rLX_buI_cwqQ51TXKFupnhTcbmHYSawk

# 문서 -> pdf
"""

import os

!pip install fpdf

from fpdf import FPDF

# 한글 폰트 경로
FONT_PATH = "NanumGothic.ttf"  # 또는 본고딕 등 TTF 파일 경로

class PDF(FPDF):
    def header(self):
        self.set_font("Nanum", '', 12)
        self.cell(0, 10, "채용 관리자 가이드", ln=True, align='C')

    def footer(self):
        self.set_y(-15)
        self.set_font("Nanum", '', 10)
        self.cell(0, 10, f'Page {self.page_no()}', align='C')

# PDF 객체 생성
pdf = PDF()

# ✅ 폰트 먼저 등록
pdf.add_font("Nanum", '', FONT_PATH, uni=True)
pdf.set_font("Nanum", '', 12)

# ✅ 페이지 추가는 폰트 설정 이후!
pdf.add_page()

# 콘텐츠
contents = [
    "1. 채용 공고 작성 가이드\n"
    "- 마이페이지 → 새공고 추가하기 → 새채용시작 버튼 클릭\n"
    "- 직무, 언어, 지역, 연봉, 채용 인원, 상세 설명, 공고 마감일 설정\n"
    "- '필터링 적용' 버튼을 누르면 조건에 맞는 인재 리스트가 표시됩니다\n"
    "- 이때 GitHub README를 읽어 필터링이 자동 적용됩니다\n",

    "2. 인재 추천 시스템 소개\n"
    "- 조건에 맞는 인재 리스트는 GitHub의 README 분석을 통해 가져옵니다\n"
    "- 관리자가 리스트 중 적합한 인재를 선택해 메일을 발송합니다\n"
    "- 이 과정에서 포트폴리오 제출 페이지 링크가 포함된 메일이 자동 생성됩니다\n"
    "- 링크에는 고유 식별 번호가 포함되어 인재를 구별할 수 있습니다\n",

    "3. 메일 자동 발송 안내\n"
    "- 구직자는 회원가입 시 GitHub 아이디로 가입합니다\n"
    "- 메일에는 자동으로 포트폴리오 제출 페이지 링크가 포함됩니다\n"
    "- 수락 유도 방식으로는 간단한 안내 및 클릭 유도 문구 포함\n"
]

for section in contents:
    pdf.multi_cell(0, 10, section)
    pdf.ln()

# PDF 저장
pdf.output("채용_관리자_가이드.pdf")

"""# 챗봇_ 기본"""

!pip install -U langchain langchain-community

!pip install pypdf

!pip install chromadb

from langchain.document_loaders import PyPDFLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.vectorstores import Chroma
from langchain.embeddings import OpenAIEmbeddings
from langchain.chat_models import ChatOpenAI
from langchain.chains import RetrievalQA

openai_api_key=""

# 1. PDF 로드 및 텍스트 추출
pdf_path = "채용_관리자_가이드.pdf"
loader = PyPDFLoader(pdf_path)
documents = loader.load()

# 2. 텍스트 쪼개기 (300자 단위)
text_splitter = RecursiveCharacterTextSplitter(chunk_size=300, chunk_overlap=50)
texts = text_splitter.split_documents(documents)

openai_api_key = os.getenv("OPENAI_API_KEY")

# 3. 임베딩 및 벡터 DB 생성 (OpenAI API 키 필요)
embedding = OpenAIEmbeddings(openai_api_key=openai_api_key)
vectorstore = Chroma.from_documents(texts, embedding)

# 4. Retrieval QA 체인 생성
retriever = vectorstore.as_retriever(search_kwargs={"k": 1})
llm = ChatOpenAI(model_name="gpt-3.5-turbo", temperature=0, openai_api_key=openai_api_key)
qa_chain = RetrievalQA.from_chain_type(llm=llm, retriever=retriever, return_source_documents=True)

# 5. 질문 예시
query = "채용 공고 작성 방법 알려줘"
result = qa_chain.invoke({"query": query})

print("질문:", result["query"])
print("답변:", result["result"])
print("참고 문서:", [doc.page_content[:100] + "..." for doc in result["source_documents"]])

"""# 챗봇_프롬프트 추가"""

!pip install langchain_openai

from langchain.document_loaders import PyPDFLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.vectorstores import Chroma
from langchain_openai import OpenAIEmbeddings, ChatOpenAI  # 최신 langchain-openai 사용 권장
from langchain.chains import RetrievalQA
from langchain.prompts.chat import (
    ChatPromptTemplate,
    SystemMessagePromptTemplate,
    HumanMessagePromptTemplate,
)

# 0. OpenAI API 키 설정
openai_api_key = openai_api_key

# 1. PDF 로드 및 텍스트 추출
pdf_path = "채용_관리자_가이드.pdf"
loader = PyPDFLoader(pdf_path)
documents = loader.load()

# 2. 텍스트 쪼개기 (300자 단위, 50자 중첩)
text_splitter = RecursiveCharacterTextSplitter(chunk_size=300, chunk_overlap=100)
texts = text_splitter.split_documents(documents)

# 3. 임베딩 및 벡터 DB 생성
embedding = OpenAIEmbeddings(openai_api_key=openai_api_key)
vectorstore = Chroma.from_documents(texts, embedding)

# 4. Retriever 생성
retriever = vectorstore.as_retriever(search_kwargs={"k": 1})

# 5. LLM 생성
llm = ChatOpenAI(model_name="gpt-3.5-turbo", temperature=0, openai_api_key=openai_api_key)

# 6. 커스텀 프롬프트 만들기
system_template = """
당신은 취업 웹사이트 고객센터 상담원 역할을 수행하는 AI 챗봇입니다.
당신의 임무는 아래 문서 요약 내용을 바탕으로 사용자 질문에 친절하고 정확하게 답변하는 것입니다.

다음의 규칙을 반드시 따르세요:

1. 문서 요약(summaries)을 기반으로만 답변하세요. 모르는 내용은 "죄송하지만 해당 정보는 제공되지 않았습니다."라고 답하세요.
2. 필요한 경우 항목이나 단계는 번호를 붙여 나열해 주세요.
3. 문서 기반 정보에 출처가 있으면 답변 마지막에 `"출처: 페이지 번호"` 형식으로 마크다운 형태로 표시해 주세요.
4. 답변은 존댓말을 사용하고, 친절하고 명확하게 말하세요.
5. 한국어로 작성하며 마크다운 포맷(예: 리스트, 강조, 구분선 등)을 적극 활용해 가독성을 높이세요.

문서 요약:
----------------------
{summaries}
----------------------

질문에 대한 답변:
"""

system_message_prompt = SystemMessagePromptTemplate.from_template(system_template)
human_message_prompt = HumanMessagePromptTemplate.from_template("{question}")
chat_prompt = ChatPromptTemplate.from_messages([system_message_prompt, human_message_prompt])

# 7. RetrievalQA 체인 생성 (커스텀 프롬프트 적용)
chain_type_kwargs = {
    "prompt": chat_prompt,
    "document_variable_name": "summaries",
}
qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=retriever,
    chain_type="stuff",
    return_source_documents=True,
    chain_type_kwargs=chain_type_kwargs,
    input_key="question",
)

# 8. 질문 실행
query = "채용 공고 어떻게 작성해?"
result = qa_chain.invoke({"question": query})

# 9. 결과 출력
print("답변:\n", result["result"])
print("\n출처 문서 내용:\n", result["source_documents"][0].page_content)
